define(function () {
  return [
    {
      'default': {
        name: 'form1',
        label: 'Form 1',
        _elements: [
          {
            'default': {
              name: 'id',
              type: 'hidden'
            }
          },
          {
            'default': {
              name: 'url',
              label: 'URL',
              type: 'url',
              defaultValue: 'https://blinkm.co/ron',
              placeholderText: 'http://host/path?query'
            }
          },
          {
            'default': {
              name: 'hiddentext',
              label: 'Hidden Field',
              type: 'text',
              hidden: true,
              defaultValue: "Test"
            }
          },
          {
            'default': {
              name: 'email',
              label: 'Email',
              type: 'email',
              defaultValue: 'ron@blinkmobile.com.au',
              placeholderText: 'user@host',
              section: 'account'
            }
          },
          {
            'default': {
              name: 'password',
              label: 'Password',
              type: 'password',
              defaultValue: 'secret',
              placeholderText: 'password',
              section: 'account'
            }
          },
          {
            'default': {
              name: 'streetAddress',
              label: 'Street Address',
              type: 'textarea',
              defaultValue: 'Suite 2\r\n125 Donnison Street',
              placeholderText: 'cupboard under the stairs',
              section: 'address'
            }
          },
          {
            'default': {
              name: 'city',
              label: 'City',
              type: 'text',
              defaultValue: 'Gosford',
              placeholderText: 'city',
              section: 'address'
            }
          },
          {
            'default': {
              name: 'telephone',
              label: 'Telephone',
              type: 'telephone',
              defaultValue: '+61 439 901 787',
              placeholderText: '+61 412 345 678'
            }
          },
          {
            'default': {
              name: 'number',
              label: 'Number',
              type: 'number',
              min: 15,
              max: 400,
              step: 5,
              defaultValue: 35,
              placeholderText: '20'
            }
          },
          {
            'default': {
              name: 'number2',
              label: 'Number with slider',
              type: 'number',
              useSlider: "1",
              max: "100",
              defaultValue: "1",
              placeholderText: '20'
            }
          },
          {
            'default': {
              name: 'number3',
              label: 'Number without default',
              type: 'number',
              min: "15",
              max: "400",
              step: "5",
              defaultValue: ""
            }
          },
          {
            'default': {
              name: 'currency',
              label: 'Currency',
              type: 'number',
              minDecimals: 2,
              maxDecimals: 2,
              defaultValue: '876.54',
              placeholderText: '20.00'
            }
          },
          {
            'default': {
              name: 'heading',
              type: 'heading',
              level: 1,
              text: 'Heading!'
            }
          },
          {
            'default': {
              name: 'heading2',
              type: 'heading',
              level: 2,
              text: 'h2'
            }
          },
          {
            'default': {
              name: 'heading3',
              type: 'heading',
              headingType: 2,
              text: 'h3'
            }
          },
          {
            'default': {
              name: 'heading4',
              type: 'heading',
              headingType: 2,
              text: 'h3 with Small Text',
              headingSmallText: "<span>Small Text</span>"
            }
          },
          {
            'default': {
              name: 'message',
              type: 'message',
              html: 'This is <strong>static</strong> text.'
            }
          },
          {
            'default': {
              name: 'calculation',
              label: 'Calculation',
              type: 'message',
              html: 'This is could be HTML generated by a <em>Behaviour</em>.',
              persist: true
            }
          }
        ],
        _sections: [
          {
            'default': {
              name: 'account',
              'class': 'myClass'
            }
          },
          {
            'default': {
              name: 'address',
              'class': 'myClass'
            }
          }
        ]
      }
    }
  ];
});
